spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
server.address=0.0.0.0

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.root=info
logging.level.org.hibernate=off
logging.level.org.springframework.orm.jpa=warn
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl=off
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.open-in-view=false
JWT_SECRET=${JWT_SECRET_KEY}

CHATGPT_SECRETKEY=${CHATGPT_SECRET_KEY}

OPENAI_URL=${OPENAI_URL}


