spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console

spring.jpa.open-in-view=false
JWT_SECRET=${JWT_SECRET_KEY}

CHATGPT_SECRETKEY=${CHATGPT_SECRET_KEY}

OPENAI_URL=${OPENAI_URL}


